# Generated by Django 3.1.5 on 2021-01-20 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogttm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field_name', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
            options={
                'ordering': ['-my_field_name'],
            },
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='DjangoBlog',
        ),
        migrations.AlterModelOptions(
            name='djangoblog',
            options={'ordering': ['-created_date']},
        ),
    ]
