# Generated by Django 3.1.5 on 2021-01-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogttm', '0003_auto_20210122_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='djangoblog',
            name='post_subject',
            field=models.ManyToManyField(to='blogttm.PostSubject'),
        ),
    ]
