# Generated by Django 3.1.5 on 2021-01-26 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogttm', '0005_auto_20210122_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post_subject', models.ManyToManyField(to='blogttm.PostSubject')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloudModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, choices=[('a', 'AWS'), ('g', 'GCP'), ('i', 'IBM'), ('o', 'Oracle'), ('c', 'Container'), ('b', 'Basic')], default='b', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post_subject', models.ManyToManyField(to='blogttm.PostSubject')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataAnalysisModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, choices=[('db', 'DataBase'), ('v', 'Visualization'), ('i', 'IBM'), ('o', 'Oracle'), ('b', 'Basic')], default='b', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post_subject', models.ManyToManyField(to='blogttm.PostSubject')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post_subject', models.ManyToManyField(to='blogttm.PostSubject')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GitModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('post_subject', models.ManyToManyField(to='blogttm.PostSubject')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cloud',
            name='author',
        ),
        migrations.RemoveField(
            model_name='cloud',
            name='post_subject',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dataanalysis',
            name='post_subject',
        ),
        migrations.RemoveField(
            model_name='django',
            name='author',
        ),
        migrations.RemoveField(
            model_name='django',
            name='post_subject',
        ),
        migrations.RemoveField(
            model_name='git',
            name='author',
        ),
        migrations.RemoveField(
            model_name='git',
            name='post_subject',
        ),
        migrations.DeleteModel(
            name='CaseStudy',
        ),
        migrations.DeleteModel(
            name='Cloud',
        ),
        migrations.DeleteModel(
            name='DataAnalysis',
        ),
        migrations.DeleteModel(
            name='Django',
        ),
        migrations.DeleteModel(
            name='Git',
        ),
    ]
