# Generated by Django 3.1.5 on 2021-01-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogttm', '0006_auto_20210127_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTTM',
        ),
        migrations.AddField(
            model_name='casestudymodels',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cloudmodels',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dataanalysismodels',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='djangocontentsmodels',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gitmodels',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='casestudymodels',
            name='post_subject',
            field=models.ManyToManyField(blank=True, to='blogttm.PostSubject'),
        ),
        migrations.AlterField(
            model_name='cloudmodels',
            name='post_subject',
            field=models.ManyToManyField(blank=True, to='blogttm.PostSubject'),
        ),
        migrations.AlterField(
            model_name='dataanalysismodels',
            name='post_subject',
            field=models.ManyToManyField(blank=True, to='blogttm.PostSubject'),
        ),
        migrations.AlterField(
            model_name='djangocontentsmodels',
            name='post_subject',
            field=models.ManyToManyField(blank=True, to='blogttm.PostSubject'),
        ),
        migrations.AlterField(
            model_name='gitmodels',
            name='post_subject',
            field=models.ManyToManyField(blank=True, to='blogttm.PostSubject'),
        ),
    ]
